name: lab02
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Generating a report for a lab02"
      - run: pip install nbconvert
      - run: jupyter nbconvert --to pdf  lab01/1_1.ipynb
      