name: lab02
on: push
jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Generating a report for a lab02"
      - run: pip install nbconvert
      - run: sudo apt-get install pandoc texlive-xetex
      - run: python -m nbconvert --to pdf lab01/1_1.ipynb