name: lab02
on: push
jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install nbconvert
        run: pip install nbconvert
      - name: Install Pandoc and XeLaTeX
        run: sudo apt-get install pandoc texlive-xetex
      - name: Generate a report for a lab01
        run: python -m nbconvert --to pdf lab01/1_1.ipynb
      - name: Publish the generated report
        uses: actions/upload-artifact@v4
        with:
          path: lab01/1_1.ipynb