name: lab02
on: push
jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: echo "Generating a report for a lab02"
      - run: pip install nbconvert
      - run: python -m nbconvert --to pdf lab01/1_1.ipynb
