name: lab_01
on: push
jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install python packages
        run: pip install pint matplotlib scipy ipykernel
      - name: Install nbconvert
        run: pip install nbconvert
      - name: Install Pandoc, LaTeX, Inkscape
        run: sudo apt-get install pandoc texlive-xetex inkscape
      - name: Execute the notebook and generate a PDF report
        run: python -m nbconvert --to pdf --execute lab_01/pint_and_boiling_point.ipynb 
      - name: Publish the generated report
        uses: actions/upload-artifact@v4
        with:
          path: lab_01/pint_and_boiling_point.pdf
